/*
Nuedaf_EventExposure

UEDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uedaf

import (
	"encoding/json"
)

// UeInformation Represents load level information of a given NF instance.
type UeInformation struct {
	// Identifies a SUPI for an UE. 
	Supi *string `json:"supi,omitempty"`
	// Cell identifier to which the UE is connected 
	CellId *string `json:"cell_id,omitempty"`
	// PLMN indicator
	Plmn *string `json:"plmn,omitempty"`
	// Status indicator
	Status *string `json:"status,omitempty"`
	// Status timestamp indicator
	StatusTimestamp *string `json:"status_timestamp,omitempty"`
}

// NewUeInformation instantiates a new UeInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUeInformation() *UeInformation {
	this := UeInformation{}
	return &this
}

// NewUeInformationWithDefaults instantiates a new UeInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUeInformationWithDefaults() *UeInformation {
	this := UeInformation{}
	return &this
}

// GetSupi returns the Supi field value if set, zero value otherwise.
func (o *UeInformation) GetSupi() string {
	if o == nil || o.Supi == nil {
		var ret string
		return ret
	}
	return *o.Supi
}

// GetSupiOk returns a tuple with the Supi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeInformation) GetSupiOk() (*string, bool) {
	if o == nil || o.Supi == nil {
		return nil, false
	}
	return o.Supi, true
}

// HasSupi returns a boolean if a field has been set.
func (o *UeInformation) HasSupi() bool {
	if o != nil && o.Supi != nil {
		return true
	}

	return false
}

// SetSupi gets a reference to the given string and assigns it to the Supi field.
func (o *UeInformation) SetSupi(v string) {
	o.Supi = &v
}

// GetCellId returns the CellId field value if set, zero value otherwise.
func (o *UeInformation) GetCellId() string {
	if o == nil || o.CellId == nil {
		var ret string
		return ret
	}
	return *o.CellId
}

// GetCellIdOk returns a tuple with the CellId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeInformation) GetCellIdOk() (*string, bool) {
	if o == nil || o.CellId == nil {
		return nil, false
	}
	return o.CellId, true
}

// HasCellId returns a boolean if a field has been set.
func (o *UeInformation) HasCellId() bool {
	if o != nil && o.CellId != nil {
		return true
	}

	return false
}

// SetCellId gets a reference to the given string and assigns it to the CellId field.
func (o *UeInformation) SetCellId(v string) {
	o.CellId = &v
}

// GetPlmn returns the Plmn field value if set, zero value otherwise.
func (o *UeInformation) GetPlmn() string {
	if o == nil || o.Plmn == nil {
		var ret string
		return ret
	}
	return *o.Plmn
}

// GetPlmnOk returns a tuple with the Plmn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeInformation) GetPlmnOk() (*string, bool) {
	if o == nil || o.Plmn == nil {
		return nil, false
	}
	return o.Plmn, true
}

// HasPlmn returns a boolean if a field has been set.
func (o *UeInformation) HasPlmn() bool {
	if o != nil && o.Plmn != nil {
		return true
	}

	return false
}

// SetPlmn gets a reference to the given string and assigns it to the Plmn field.
func (o *UeInformation) SetPlmn(v string) {
	o.Plmn = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UeInformation) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeInformation) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UeInformation) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *UeInformation) SetStatus(v string) {
	o.Status = &v
}

// GetStatusTimestamp returns the StatusTimestamp field value if set, zero value otherwise.
func (o *UeInformation) GetStatusTimestamp() string {
	if o == nil || o.StatusTimestamp == nil {
		var ret string
		return ret
	}
	return *o.StatusTimestamp
}

// GetStatusTimestampOk returns a tuple with the StatusTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UeInformation) GetStatusTimestampOk() (*string, bool) {
	if o == nil || o.StatusTimestamp == nil {
		return nil, false
	}
	return o.StatusTimestamp, true
}

// HasStatusTimestamp returns a boolean if a field has been set.
func (o *UeInformation) HasStatusTimestamp() bool {
	if o != nil && o.StatusTimestamp != nil {
		return true
	}

	return false
}

// SetStatusTimestamp gets a reference to the given string and assigns it to the StatusTimestamp field.
func (o *UeInformation) SetStatusTimestamp(v string) {
	o.StatusTimestamp = &v
}

func (o UeInformation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Supi != nil {
		toSerialize["supi"] = o.Supi
	}
	if o.CellId != nil {
		toSerialize["cell_id"] = o.CellId
	}
	if o.Plmn != nil {
		toSerialize["plmn"] = o.Plmn
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.StatusTimestamp != nil {
		toSerialize["status_timestamp"] = o.StatusTimestamp
	}
	return json.Marshal(toSerialize)
}

type NullableUeInformation struct {
	value *UeInformation
	isSet bool
}

func (v NullableUeInformation) Get() *UeInformation {
	return v.value
}

func (v *NullableUeInformation) Set(val *UeInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableUeInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableUeInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUeInformation(val *UeInformation) *NullableUeInformation {
	return &NullableUeInformation{value: val, isSet: true}
}

func (v NullableUeInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUeInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


