/*
Nuedaf_EventExposure

UEDAF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uedaf

import (
	"encoding/json"
)

// UedafCreatedEventSubscription Data within a create UEDAF event subscription response
type UedafCreatedEventSubscription struct {
	Subscription UedafEventSubscription `json:"subscription"`
	// String providing an URI formatted according to RFC 3986.
	SubscriptionId string `json:"subscriptionId"`
	ReportEvent *UedafEventReport `json:"reportEvent,omitempty"`
}

// NewUedafCreatedEventSubscription instantiates a new UedafCreatedEventSubscription object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUedafCreatedEventSubscription(subscription UedafEventSubscription, subscriptionId string) *UedafCreatedEventSubscription {
	this := UedafCreatedEventSubscription{}
	this.Subscription = subscription
	this.SubscriptionId = subscriptionId
	return &this
}

// NewUedafCreatedEventSubscriptionWithDefaults instantiates a new UedafCreatedEventSubscription object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUedafCreatedEventSubscriptionWithDefaults() *UedafCreatedEventSubscription {
	this := UedafCreatedEventSubscription{}
	return &this
}

// GetSubscription returns the Subscription field value
func (o *UedafCreatedEventSubscription) GetSubscription() UedafEventSubscription {
	if o == nil {
		var ret UedafEventSubscription
		return ret
	}

	return o.Subscription
}

// GetSubscriptionOk returns a tuple with the Subscription field value
// and a boolean to check if the value has been set.
func (o *UedafCreatedEventSubscription) GetSubscriptionOk() (*UedafEventSubscription, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subscription, true
}

// SetSubscription sets field value
func (o *UedafCreatedEventSubscription) SetSubscription(v UedafEventSubscription) {
	o.Subscription = v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *UedafCreatedEventSubscription) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *UedafCreatedEventSubscription) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *UedafCreatedEventSubscription) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

// GetReportEvent returns the ReportEvent field value if set, zero value otherwise.
func (o *UedafCreatedEventSubscription) GetReportEvent() UedafEventReport {
	if o == nil || o.ReportEvent == nil {
		var ret UedafEventReport
		return ret
	}
	return *o.ReportEvent
}

// GetReportEventOk returns a tuple with the ReportEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UedafCreatedEventSubscription) GetReportEventOk() (*UedafEventReport, bool) {
	if o == nil || o.ReportEvent == nil {
		return nil, false
	}
	return o.ReportEvent, true
}

// HasReportEvent returns a boolean if a field has been set.
func (o *UedafCreatedEventSubscription) HasReportEvent() bool {
	if o != nil && o.ReportEvent != nil {
		return true
	}

	return false
}

// SetReportEvent gets a reference to the given UedafEventReport and assigns it to the ReportEvent field.
func (o *UedafCreatedEventSubscription) SetReportEvent(v UedafEventReport) {
	o.ReportEvent = &v
}

func (o UedafCreatedEventSubscription) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["subscription"] = o.Subscription
	}
	if true {
		toSerialize["subscriptionId"] = o.SubscriptionId
	}
	if o.ReportEvent != nil {
		toSerialize["reportEvent"] = o.ReportEvent
	}
	return json.Marshal(toSerialize)
}

type NullableUedafCreatedEventSubscription struct {
	value *UedafCreatedEventSubscription
	isSet bool
}

func (v NullableUedafCreatedEventSubscription) Get() *UedafCreatedEventSubscription {
	return v.value
}

func (v *NullableUedafCreatedEventSubscription) Set(val *UedafCreatedEventSubscription) {
	v.value = val
	v.isSet = true
}

func (v NullableUedafCreatedEventSubscription) IsSet() bool {
	return v.isSet
}

func (v *NullableUedafCreatedEventSubscription) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUedafCreatedEventSubscription(val *UedafCreatedEventSubscription) *NullableUedafCreatedEventSubscription {
	return &NullableUedafCreatedEventSubscription{value: val, isSet: true}
}

func (v NullableUedafCreatedEventSubscription) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUedafCreatedEventSubscription) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


